# For Atom Feed
# domain: oecd-icio.cloudapp.net
domain: www.icio.oecd.org
author: OECD STI/EAS
email: stan.contact@oecd.org
title: OECD ICIO

# standard jekyll configuration

permalink: /articles/:title
highlighter: pygments
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- rmarkdown

include:
- _stylesheets
- _javascript

markdown: rdiscount

sass:
  sass_dir: assets/vendor/
  style: :compressed

# Custom site configuration
lang: en

# baseurl: /kit
# baseurl: /icioapp2015
baseurl: 
